---
- name: Basic Cisco IOS Configuration
  hosts: routers
  gather_facts: no
  connection: network_cli

  vars:
    hostname: "example_hostname"
    domain_name: "example.com"
    motd_banner: "example_banner"
    enable_secret: "password"
    local_users:
      - name: "username"
        secret: "password"
    rsa_modulus: 1024
    ssh_version: 2
    ssh_timeout: 120
    ssh_auth_retries: 3
    console_exec_timeout: [3, 0]
    vty_range: "0 15"
    line_privilege: 0

  tasks:
    - name: Disable DNS lookup and CDP
      cisco.ios.ios_config:
        lines:
          - no ip domain-lookup
          - no cdp run

    - name: Set hostname, domain name and MOTD banner
      cisco.ios.ios_config:
        lines:
          - hostname {{ hostname }}
          - ip domain name {{ domain_name }}
          - banner motd #{{ motd_banner }}#

    - name: Enable system logging
      cisco.ios.ios_config:
        lines:
          - logging on

    - name: Configure enable secret
      cisco.ios.ios_config:
        lines:
          - enable secret {{ enable_secret }}

    - name: Create local user(s)
      cisco.ios.ios_config:
        lines:
          - username {{ item.name }} privilege 0 secret {{ item.secret }}
      loop: "{{ local_users }}"

    - name: Generate RSA key for SSH
      cisco.ios.ios_config:
        lines:
          - crypto key generate rsa general-keys modulus {{ rsa_modulus }}

    - name: Harden SSH parameters
      cisco.ios.ios_config:
        lines:
          - ip ssh version {{ ssh_version }}
          - ip ssh time-out {{ ssh_timeout }}
          - ip ssh authentication-retries {{ ssh_auth_retries }}

    - name: Configure console line
      cisco.ios.ios_config:
        parents:
          - line console 0
        lines:
          - login local
          - exec-timeout {{ console_exec_timeout[0] }} {{ console_exec_timeout[1] }}
          - privilege level {{ line_privilege }}
          - logging synchronous

    - name: Configure VTY lines
      cisco.ios.ios_config:
        parents:
          - line vty {{ vty_range }}
        lines:
          - login local
          - transport input ssh
          - exec-timeout {{ console_exec_timeout[0] }} {{ console_exec_timeout[1] }}
          - privilege level {{ line_privilege }}
          - logging synchronous

    - name: Encrypt plaintext passwords
      cisco.ios.ios_config:
        lines:
          - service password-encryption

    - name: Save running-config to startup-config
      cisco.ios.ios_config:
        save_when: modified
